### ISSUE TITLE
Allow companies to select industry

### ISSUE THREAD

**Issue by sktran** [multiparty/web-mpc#121]
- [x] Add dropdown menu for industries on the frontend.
- [x] Allow analyst to add/update list of industries on analyst UI.
- [x] Link the industry self-selection to the cohorts in the backend.

**Comment by lucyq** [comment]
Working on back-end.

**Comment by lucyq** [comment]
@p-flock doing the front-end.

**Comment by sktran** [comment]
Note the order of operations from @lucyq:
> 1.) i'm going to merge the auto-testing work we did into master. 2.) merge pacesetters into master once tests are properly running 3.) begin working on industry self-selection on the back-end

**Comment by lucyq** [comment]
Completed. See PR #129
