### ISSUE TITLE
Add tooltip messages for cells.

### ISSUE THREAD

**Issue by jgyou-bu** [multiparty/web-mpc#13]
The tooltip text/data validation messages should be a part of the template file for the overall tables. Text should be the same as the sample data collection Excel form.

**Comment by lapets** [comment]
Change when the tooltip appears to a click rather than mouseover. Fix lagging when the mouse leaves a cell.

**Comment by frederickjansen** [comment]
Tooltips for error messages appear on click, and disappear when moving the mouse outside of the cell.
