### ISSUE TITLE
/index: change 'session key' to something more understandable

### ISSUE THREAD

**Issue by globusharris** [multiparty/web-mpc#146]
e.g. 'BWWC 2019 Analysis ID'.

Use handlebars for this so can change depending on deployment. 

We discussed changing this to 'Company ID' and decided against this since it might signal to companies that they are identifiable by SAIL based on this ID.

**Comment by globusharris** [comment]
Should match wording to this on /manage pages as well.

**Comment by lucyq** [comment]
Should be generic and located somewhere in the config.

**Comment by globusharris** [comment]
@lucyq yep that's how I've implemented. :)

**Comment by globusharris** [comment]
Right now, handlebars only works in index.html due to server-side rendering. Working on expanding it to work for all html files now.

**Comment by lucyq** [comment]
Closed by #163
