### ISSUE TITLE
Assist in sending emails to participants automatically

### ISSUE THREAD

**Issue by KinanBab** [multiparty/web-mpc#15]
Have the front-end on the analyst side immediately send emails with links that contain session key to the users.

Possible approaches:
1. Using analyst email client (super easy but maybe not very helpful): window.open('mailto:test@example.com?subject=subject&body=body');

2. Through the analyst's gmail (https://github.com/sitepoint-editors/gmail-api-javascript-example/blob/master/02%20-%20Sending%20mail/index.html)
pros: secure
cons: analyst must insert google credentials (apiKey and clientId)

3. Through third party library (maybe mailgun https://www.mailgun.com/ : it gives 10,000 emails per month for free!). Cons: the api key will be available on the client side, but their could be possible work arounds.

**Comment by lapets** [comment]
Another possible solution: generate a complete spreadsheet containing the following (to be used in a mail merge):
* the link;
* the email (possibly).

**Comment by lapets** [comment]
Another issue: can no longer show the identifiers of those who submitted in the session tracker that is available to the analyzer.

**Comment by lapets** [comment]
Will proceed with mail merge approach: generate a spreadsheet with links. This is interdependent with #9 and #10.

**Comment by lapets** [comment]
Do not show URL or contributor identifier in the status log visible to the analyzer party. Only show the latest submission time for any given contributor.

**Comment by KinanBab** [comment]
Should be all done in participation-code branch
