### ISSUE TITLE
/index: add totals check for all tables

### ISSUE THREAD

**Issue by globusharris** [multiparty/web-mpc#152]
Currently just for total number of employees; should have one for each table at bottom of submission page.

**Comment by lucyq** [comment]
According to @KinanBab, this is what the UI used to look like but it was changed for some reason. @frederickjansen do you remember the reasoning?

**Comment by lucyq** [comment]
@globusharris not sure if this needs to be implemented. we should ask Shereen & Frederick on slack.

**Comment by globusharris** [comment]
Not doing this.
