### ISSUE TITLE
Show semantic discrepancies across tables.

### ISSUE THREAD

**Issue by lapets** [multiparty/web-mpc#18]
Once the "verified" checkbox is checked, verify that there are no employees that have zero compensation or tenure (or that there are no tenure/compensation amounts that do not correspond to employees).

**Comment by lapets** [comment]
The erroneous conditions for each cell are as follows.
- [ ] For all tables except bonus, the cell must be either zero in all tables, or non-zero in all tables.
- [ ] For the bonus table, it can only be non-zero if the other tables are non-zero.

**Comment by KinanBab** [comment]
@lapets @frederickjansen what would be a suitable error message for this and how do we display it?

**Comment by KinanBab** [comment]
simple version of this is done, needs more work on displaying the errors

**Comment by lapets** [comment]
Superseded by #43.
