### ISSUE TITLE
Total isn't recalculated after invalid field

### ISSUE THREAD

**Issue by frederickjansen** [multiparty/web-mpc#23]
To reproduce:
- Enter invalid data into table
- Check totals table, should be NaN
- Change invalid data to number

The totals table should update but does not.

**Comment by KinanBab** [comment]
In participation-code branch

**Comment by lapets** [comment]
Change "NaN" to something more descriptive (see template).

**Comment by KinanBab** [comment]
The template does not take this case into account. 
If you force a cell to have a number, the final total will appear as "#VALUE!"
