### ISSUE TITLE
Minor cosmetic fixes.

### ISSUE THREAD

**Issue by lapets** [multiparty/web-mpc#33]
- [x] Change header to "Latinx".
- [x] Add new logo.
- [x] Add correct questions.
- [x] Add "Drag and drop completed template file here".
- [x] Add correct language above the questions.
- [x] Ensure questions are not pre-answered.
- [x] Change subtitle to "100% Talent Data Submission" and title to "Boston Women's Workforce Council".

**Comment by frederickjansen** [comment]
Both items are on master. Will keep ticket open in case we want to add more cosmetic fixes.
