### ISSUE TITLE
Change session and password encoding to base32

### ISSUE THREAD

**Issue by frederickjansen** [multiparty/web-mpc#34]
Mayank recommended making the strings shorter by using base32. Base64 is also a possibility, but needs to be made safe for URLs.

**Comment by jgyou-bu** [comment]
@frederickjansen - I am currently using a Base32 library for the encoding:
https://github.com/agnoster/base32-js

I found two Base64 libraries - do we want to switch to the first one potentially?
- https://www.npmjs.com/package/urlsafe-base64
- https://github.com/beatgammit/base64-js

**Comment by frederickjansen** [comment]
The first base64 library would be an option. Not entirely sure what's better here, shorter tags or case-insensitivity. My gut feeling says people are less likely to make mistakes with base32.
