### ISSUE TITLE
Test the application thoroughly.

### ISSUE THREAD

**Issue by lapets** [multiparty/web-mpc#50]
- [x] Test what happens if you drag and drop after submission.
- [x] Test filling out and saving the Excel template on various OSs and using various office applications/suites.
- [x] Resave in *.xls format and test (if this does not work, try to make the message useful).
- [x] Test the application using various browsers and browser versions.
- [x] Click back and forward again after submitting or at the last stage of submission.
- [x] Test the application with ad blockers.

**Comment by KinanBab** [comment]
Tested drag and drop with sheets saved by libreoffice on both linux (centos) and windows.

**Comment by jgyou-bu** [comment]
Tested drag and drop with Windows 10/Office 2016 on Edge, Firefox, and Chrome. Parse and display of tables works with both xls and xlsx js files. (Used staging.100talent.org to test.)

**Comment by lapets** [comment]
Removed test about JavaScript being disabled.

**Comment by sktran** [comment]
Last removed task duplicated #66.
