### ISSUE TITLE
Fix spreadsheet header scroll

### ISSUE THREAD

**Issue by frederickjansen** [multiparty/web-mpc#57]
I broke something when changing the table sizing to automatically resize the card container. You can no longer scroll the page when your mouse is hovered over any of the spreadsheet headers.

**Comment by KinanBab** [comment]
I looked at this briefly, I cannot really tell what went wrong. It seems the table header is capturing the scrolling event instead of the page. Before this was not an issue because the table had its own scrolling, so this was the correct behaviour.

**Comment by KinanBab** [comment]
the issues is caused by the overflow:hidden property being set in  ResizeSensor.js
using overflow-x:hidden or overflow-y: hidden does not seem to solve it.
Looking for alternative solutions.
