### ISSUE TITLE
When verification checkbox is clicked and there are warnings or errors, show an alert.

### ISSUE THREAD

**Issue by lapets** [multiparty/web-mpc#6]
Use a Bootstrap or Alertify notification if there are any warnings or errors in the cells. Do not allow the checkbox to be checked until all errors are removed. The check for errors should be modular and should call the function(s) that perform error checking.

The notification should indicate what the error or warning is (errors are unfilled boxes or boxes filled with non-numeric values, warnings are out-of-range values such as an employee count over 10,000).

**Comment by ishaikh1** [comment]
The alerts were previously there. Changed them into alertify alerts.

**Comment by ishaikh1** [comment]
Alerts work as described above. They just do not check for employee counts over 10000, but that was discussed to not be of concern.

**Comment by lapets** [comment]
It remains to merge this branch into master.

**Comment by KinanBab** [comment]
In pull request #20
